//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermaFx.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HermaFx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;RSAParameters xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///	&lt;Modulus&gt;s1aZ3Wi16NOGMnnoKZa5z2POA0UzmhRcjn4rTD7mfM5n6fimhHHY/Js1dogiQiL9kzndJosSeqJV3kAp1CdY9L1q18BQI/rhA1zLjp9sPpfVAbomzQEAXVXkjL6o7NTYvp/hNMXMN86sEoIdMlk9TKgGlnFyBF1PDuAo9F8Qxq0=&lt;/Modulus&gt;
        ///	&lt;P&gt;8WLTkfZBZD4xNHqm5oxxvNlMxK7Gp4lMwyJPzgEMsWaf6uOLbdu1V/EdsUs5XJLMBOn7VhPZDYyEdSklJlyvQQ==&lt;/P&gt;
        ///	&lt;Q&gt;vjIdNI+XMoVXkx38+RKWNJ/tRrPCRK8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RSAKey {
            get {
                return ResourceManager.GetString("RSAKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mitt
        ///that
        ///with
        ///they
        ///this
        ///have
        ///from
        ///word
        ///what
        ///were
        ///when
        ///your
        ///said
        ///there
        ///each
        ///which
        ///their
        ///will
        ///other
        ///about
        ///many
        ///then
        ///them
        ///these
        ///some
        ///would
        ///make
        ///like
        ///into
        ///time
        ///look
        ///more
        ///write
        ///number
        ///could
        ///people
        ///than
        ///first
        ///water
        ///been
        ///call
        ///find
        ///long
        ///down
        ///come
        ///made
        ///part
        ///over
        ///sound
        ///take
        ///only
        ///little
        ///work
        ///know
        ///place
        ///year
        ///live
        ///back
        ///give
        ///most
        ///very
        ///after
        ///thing
        ///just
        ///name
        ///good
        ///sentence
        ///think
        ///great
        ///where
        ///help
        ///through
        ///much
        ///before
        ///line
        ///right
        ///mean
        ///same
        ///tell
        ///foll [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Wordlist {
            get {
                return ResourceManager.GetString("Wordlist", resourceCulture);
            }
        }
    }
}
